config/routes.rb
Rails.application.routes.draw do
  resources :courses do
    resources :weeks
  end
  resources :weeks do
    resources :lessons
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ActiveRecord::Base
  has_many :weeks
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :week
end

app/models/week.rb
class Week < ActiveRecord::Base
  belongs_to :course
  has_many :lessons

  def previous
    self.course.weeks.where("weeks.id < ?", self.id).order('created_at asc').last
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]
  def index
    @courses = Course.all
  end
  def show
    @weeks = @course.weeks
  end
  def create
    @course = Course.new(course_params)
    if @course.save
      flash[:notice] = "Course saved successfully!"
      redirect_to courses_path
    else
      flash[:alert] = "FAIL to save"
      render :new
    end
  end
  def new
    @course = Course.new
  end
  def edit
  end
  def update
    if @course.update(course_params)
      flash[:notice] = "Update saved successfully!"
      redirect_to courses_path
    else
      flash[:alert] = "FAIL to update"
      render :edit
    end
  end

  def destroy
    @course.weeks.each { |week| week.destroy }
    if @course.destroy
      flash[:notice] = "Course Deleted"
      redirect_to courses_path
    else
      flash[:alert] = "FAIL to delete"
    end
  end

  private
  def set_course
    @course = Course.find(params[:id])
  end
  def course_params
    params.require(:course).permit(:title, :teacher)
  end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :set_lesson, only: [:show, :edit, :update, :destroy]

  def index
    @lessons = Lesson.all
  end

  def show
  end

  def new
    @week = Week.find(params[:week_id])
    @lesson = @week.lessons.new
  end

  def edit
  end

  def create
    @week = Week.find(params[:week_id])
    @lesson = @week.lessons.new(lesson_params)
    if @lesson.save
      flash[:notice] = "Lesson saved successfully!"
      redirect_to week_path(@week)
    else
      flash[:alert] = "FAIL to save"
      render :new
    end
  end

  def update
    @week = Week.find(params[:week_id])
    @lesson = Lesson.find(params[:id])
    if @lesson.update(lesson_params)
      flash[:notice] = "Update saved successfully"
      redirect_to week_path(@week)
    else
      flash[:alert] = "fail to update"
      render :edit
    end
  end

  def destroy
    @lesson = Lesson.find(params[:id])
    @week = @lesson.week
    if @lesson.destroy
      flash[:notice] = 'Lesson was successfully destroyed.'
      redirect_to week_path(@week)
    end
  end

  private
    def set_lesson
      @lesson = Lesson.find(params[:id])
      @week = @lesson.week
    end

    def lesson_params
      params.require(:lesson).permit(:title, :content, :week_id)
    end
end

app/controllers/weeks_controller.rb
class WeeksController < ApplicationController
  
  def index
    @weeks = Week.all
  end
  def show
    @week = Week.find(params[:id])
    @course = @week.course
  end
  def create
    @course = Course.find(params[:course_id])
    @week = @course.weeks.new(week_params)
    if @week.save
      flash[:notice] = "Week saved successfully!"
      redirect_to course_path(@course)
    else
      flash[:alert] = "FAIL to save"
      render :new
    end
  end
  def new
    @course = Course.find(params[:course_id])
    @week = @course.weeks.new
  end
  def edit
    @course = Course.find(params[:course_id])
    @week = Week.find(params[:id])
  end
  def update
    @course = Course.find(params[:course_id])
    @week = Week.find(params[:id])
    if @week.update(week_params)
      flash[:notice] = "Update saved successfully!"
      redirect_to course_path(@course)
    else
      flash[:alert] = "FAIL to update"
      render :edit
    end
  end
  def destroy
    @course = @week.course
    @week.lessons.each { |lesson| lesson.destroy }
    if @week.destroy
      flash[:notice] = "Week Deleted"
      redirect_to course_path(@course)
    else
      flash[:alert] = "FAIL to delete"
    end
  end
  private
  def week_params
    params.require(:week).permit(:title, :course_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/views/courses/_form.html.erb
<%= form_for(@course) do |f| %>
<div class="field">
  <%= f.label :title %>
  <%= f.text_field :title %>
</div>
<div class="">
  <%= f.label :teacher %>
  <%= f.text_field :teacher %>
</div>
<br>
<div class="actions">
  <%= f.submit %>
</div>
<% end %>

app/views/courses/edit.html.erb
<%= flash[:alert] %>
<h1>Edit Course</h1>
<hr>
<%= render 'form' %>
<hr>
<%= link_to 'Back to Homepage', courses_path %>

app/views/courses/index.html.erb
<%= flash[:notice] %>
<%= flash[:alert] %>

<% content_for(:navbar) do %>
  <ul>
    <li><a href="/courses">Home</a></li>
  </ul>
<% end %>
<h1>Courses Page</h1>
<hr>
<ul>
  <% @courses.each do |course| %>
    <li><%= course.title %> taught by <%= course.teacher %> | <%= link_to "Course Page", course_path(course) %></li>
  <% end %>
</ul>
<hr>
<%= link_to "Add a Course", new_course_path %>

app/views/courses/new.html.erb
<%= flash[:alert] %>
<h1>New Course</h1>
<hr>
<%= render 'form' %>
<hr>
<%= link_to 'Back to Homepage', courses_path %>

app/views/courses/show.html.erb
<h1><%= @course.title %> Page</h1>

<ol>
  <% @weeks.each do |week| %>
  <li><%= week.title %> | <%= link_to "View Week", course_week_path(@course, week) %></li>
  <% end %>
</ol>

<%= link_to "Edit", edit_course_path(@course) %> | <%= link_to "Delete", course_path(@course), :data => {:confirm => "You Sure?", :method => 'delete'} %> | <%= link_to "Add a Week", new_course_week_path(@course) %>
<hr>
<%= link_to "Back to Homepage", courses_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LearnClone</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= flash[:alert] %>
  <%= flash[:notice] %>
  <%= yield :navbar %>
    <%= yield %>
  </body>
</html>

app/views/lessons/_form.html.erb
<%= form_for [@week, @lesson] do |f| %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :content %>
    <%= f.text_area :content %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lessons/edit.html.erb
<h1>Editing Lesson</h1>

<%= render 'form' %>

<%= link_to 'Show', week_lesson_path %> |
<%= link_to 'Back', week_path(@week) %>

app/views/lessons/new.html.erb
<h1>New Lesson</h1>

<%= render 'form' %>

<%= link_to 'Back', week_path(@week) %>

app/views/lessons/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @lesson.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @lesson.content %>
</p>

<p>
  <strong>Week:</strong>
  <%= @lesson.week.title%>
</p>

<%= link_to 'Edit', edit_week_lesson_path(@lesson) %> |
<%= link_to 'Delete', week_lesson_path(@lesson),:data => {:confirm => "You sure?", :method => 'delete'} %> |
<%= link_to 'Back', week_path %>

app/views/weeks/_form.html.erb
<%= form_for [@course, @week] do |f| %>
<div class="field">
  <%= f.label :title %>
  <%= f.text_field :title %>
</div>
<br>
<%= f.submit %>
<% end %>

app/views/weeks/edit.html.erb
<%= flash[:alert] %>
<h1>Edit Week</h1>
<hr>
<%= render 'form' %>
<hr>
<%= link_to 'Back to Course', course_path(@course) %>

app/views/weeks/new.html.erb
<%= flash[:alert] %>
<h1>New Week</h1>
<hr>
<%= render 'form' %>
<hr>
<%= link_to 'Back to Course', course_path(@course) %>

app/views/weeks/show.html.erb
<% content_for(:navbar) do %>
  <ul>
    <li><a href="/courses">Home</a></li>
    <% unless @week.id == Week.first.id %>
      <li> <%= link_to 'Previous', @week.previous  %></li>
    <% end %>
  </ul>
<% end %>

<h1><%= @week.title %> Page</h1>


<ul>
  <% @week.lessons.each do |lesson| %>
  <li><%= lesson.title %> | <%= link_to "View Lesson", week_lesson_path(@week, lesson) %></li>
  <% end %>
</ul>


<%= link_to "Edit", edit_course_week_path(@course, @week) %> | <%= link_to "Delete", week_path(@week), :data => {:confirm => "You Sure?", :method => 'delete'} %> | <%= link_to "Add a Lesson", new_week_lesson_path(@week) %>
<hr>
<%= link_to "Back to Course Page", course_path(@course) %>